# Generated by Django 4.0.5 on 2022-06-05 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicDegree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Ученая степень')),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование дисциплины')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование занятия')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.IntegerField(max_length=11, primary_key=True, serialize=False, unique=True)),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('birthday_date', models.CharField(max_length=15, null=True, verbose_name='Дата рождения')),
                ('birthday_place', models.CharField(max_length=255, verbose_name='Место рождения')),
                ('registration_place', models.CharField(max_length=255, verbose_name='Адрес прописки')),
                ('cur_place', models.CharField(max_length=255, verbose_name='Адрес проживания')),
                ('phone_number', models.CharField(max_length=14, verbose_name='Номер телефона')),
                ('passport', models.CharField(max_length=20, verbose_name='Паспорт')),
                ('TIN', models.CharField(max_length=20, verbose_name='ИНН')),
                ('INIPA', models.CharField(max_length=20, verbose_name='СНИЛС')),
                ('academic_degree', models.IntegerField(max_length=11, verbose_name='Ученная степень')),
                ('contract_number', models.CharField(max_length=50, null=True, verbose_name='Номер договора')),
                ('contract_date', models.DateField(max_length=150, null=True, verbose_name='Дата договора')),
                ('fluor_date', models.DateField(max_length=150, null=True, verbose_name='Дата флюорографии')),
            ],
        ),
        migrations.CreateModel(
            name='WorkLoad',
            fields=[
                ('group_name', models.CharField(max_length=10)),
                ('hours_type', models.CharField(max_length=10)),
                ('hours', models.CharField(max_length=10)),
                ('hours_total', models.CharField(max_length=10)),
                ('semester', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=4)),
                ('id', models.ManyToManyField(max_length=11, to='workWithTables.teacher', verbose_name='id')),
                ('lesson_id', models.ManyToManyField(max_length=11, to='workWithTables.lesson')),
                ('study_id', models.ManyToManyField(max_length=11, to='workWithTables.discipline')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=60, verbose_name='Наименование учебного заведения')),
                ('edu_type', models.CharField(max_length=60)),
                ('specialization', models.CharField(max_length=60, verbose_name='Специальность')),
                ('diploma_data', models.TextField(max_length=60, verbose_name='Данные диплома')),
                ('academic_degree_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workWithTables.academicdegree')),
                ('teacher_id', models.ManyToManyField(max_length=11, to='workWithTables.teacher')),
            ],
        ),
    ]
