# Generated by Django 4.0.5 on 2022-06-05 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workWithTables', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicdegree',
            options={'verbose_name': 'Ученая степень', 'verbose_name_plural': 'Таблица ученых степеней'},
        ),
        migrations.AlterModelOptions(
            name='discipline',
            options={'verbose_name': 'Дисциплина', 'verbose_name_plural': 'Таблица дисциплин'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'Образование', 'verbose_name_plural': 'Таблица образований'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Занятие', 'verbose_name_plural': 'Таблица занятий'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Учитель', 'verbose_name_plural': 'Таблица учителей'},
        ),
        migrations.AlterModelOptions(
            name='workload',
            options={'verbose_name': 'Нагрузка', 'verbose_name_plural': 'Таблица нагрузки'},
        ),
        migrations.AddField(
            model_name='workload',
            name='teacher_id',
            field=models.ManyToManyField(max_length=11, null=True, to='workWithTables.teacher', verbose_name='id преподавателя'),
        ),
        migrations.AlterField(
            model_name='education',
            name='academic_degree_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workWithTables.academicdegree'),
        ),
        migrations.AlterField(
            model_name='education',
            name='teacher_id',
            field=models.ManyToManyField(max_length=11, null=True, to='workWithTables.teacher'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='academic_degree',
            field=models.IntegerField(verbose_name='Ученная степень'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='workload',
            name='group_name',
            field=models.CharField(max_length=10, verbose_name='Номер группы'),
        ),
        migrations.AlterField(
            model_name='workload',
            name='hours',
            field=models.CharField(max_length=10, verbose_name='Часы'),
        ),
        migrations.AlterField(
            model_name='workload',
            name='hours_total',
            field=models.CharField(max_length=10, verbose_name='Общие часы'),
        ),
        migrations.AlterField(
            model_name='workload',
            name='hours_type',
            field=models.CharField(max_length=10, verbose_name='Тип предмета'),
        ),
        migrations.RemoveField(
            model_name='workload',
            name='id',
        ),
        migrations.AddField(
            model_name='workload',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workload',
            name='lesson_id',
            field=models.ManyToManyField(max_length=11, null=True, to='workWithTables.lesson', verbose_name='id занятия'),
        ),
        migrations.AlterField(
            model_name='workload',
            name='semester',
            field=models.CharField(max_length=10, verbose_name='Семестр'),
        ),
        migrations.AlterField(
            model_name='workload',
            name='study_id',
            field=models.ManyToManyField(max_length=11, null=True, to='workWithTables.discipline', verbose_name='id дисциплины'),
        ),
        migrations.AlterField(
            model_name='workload',
            name='year',
            field=models.CharField(max_length=4, verbose_name='Год'),
        ),
    ]
