# Generated by Django 4.0.5 on 2022-06-05 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workWithTables', '0002_alter_academicdegree_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='teacher_id',
        ),
        migrations.AddField(
            model_name='education',
            name='teacher_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workWithTables.teacher'),
        ),
        migrations.RemoveField(
            model_name='workload',
            name='lesson_id',
        ),
        migrations.AddField(
            model_name='workload',
            name='lesson_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workWithTables.lesson'),
        ),
        migrations.RemoveField(
            model_name='workload',
            name='study_id',
        ),
        migrations.AddField(
            model_name='workload',
            name='study_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workWithTables.discipline'),
        ),
        migrations.RemoveField(
            model_name='workload',
            name='teacher_id',
        ),
        migrations.AddField(
            model_name='workload',
            name='teacher_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workWithTables.teacher'),
        ),
    ]
