# Generated by Django 4.0.5 on 2022-06-05 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workWithTables', '0003_remove_education_teacher_id_education_teacher_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='academic_degree_id',
            new_name='academic_degree',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='teacher_id',
            new_name='teacher',
        ),
        migrations.RenameField(
            model_name='workload',
            old_name='lesson_id',
            new_name='lesson',
        ),
        migrations.RenameField(
            model_name='workload',
            old_name='study_id',
            new_name='study',
        ),
        migrations.RenameField(
            model_name='workload',
            old_name='teacher_id',
            new_name='teacher',
        ),
    ]
