# Generated by Django 4.0.5 on 2022-06-09 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workWithTables', '0005_contract_remove_education_academic_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workWithTables.teacher', verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='academic_degree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workWithTables.academicdegree', verbose_name='Ученая степень'),
        ),
        migrations.AlterField(
            model_name='workload',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workWithTables.lesson', verbose_name='Занятие'),
        ),
        migrations.AlterField(
            model_name='workload',
            name='study',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workWithTables.discipline', verbose_name='Дисциплина'),
        ),
        migrations.AlterField(
            model_name='workload',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workWithTables.teacher', verbose_name='Преподаватель'),
        ),
    ]
