# Generated by Django 4.0.5 on 2022-06-11 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workWithTables', '0006_alter_education_teacher_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workload',
            options={'ordering': ['teacher'], 'verbose_name': 'Нагрузка', 'verbose_name_plural': 'Таблица нагрузки'},
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
