# Generated by Django 4.0.5 on 2022-06-12 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workWithTables', '0007_alter_workload_options_alter_teacher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_teacher', to='workWithTables.teacher', verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='workload',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_teachers', to='workWithTables.teacher', verbose_name='Преподаватель'),
        ),
    ]
