# Generated by Django 4.0.5 on 2022-06-12 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workWithTables', '0008_alter_education_teacher_alter_workload_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_education', to='workWithTables.teacher', verbose_name='Преподаватель'),
        ),
    ]
