# Generated by Django 4.0.5 on 2022-06-15 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workWithTables', '0010_teacher_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='academic_degree',
        ),
        migrations.AddField(
            model_name='teacher',
            name='academic_degree',
            field=models.ManyToManyField(to='workWithTables.academicdegree', verbose_name='Ученая степень'),
        ),
    ]
