# Generated by Django 4.0.5 on 2022-06-15 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workWithTables', '0011_remove_teacher_academic_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='contract',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workWithTables.contract', unique=True, verbose_name='Номер договора'),
        ),
    ]
