# Generated by Django 4.0.5 on 2022-06-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workWithTables', '0014_alter_teacher_options_alter_teacher_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Ученое звание')),
            ],
            options={
                'verbose_name': 'Ученое звание',
                'verbose_name_plural': 'Таблица ученых званий',
            },
        ),
        migrations.AlterField(
            model_name='teacher',
            name='academic_degree',
            field=models.ManyToManyField(related_name='get_teacher', to='workWithTables.academicdegree', verbose_name='Ученая степень'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='academic_rank',
            field=models.ManyToManyField(related_name='get_teacher', to='workWithTables.academicrank', verbose_name='Ученое звание'),
        ),
    ]
